@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam groupInheritance 3
hide empty methods
hide empty members

class Client {
    {static} + main(String[] args): void
    + Client(String victimFile, String messageFile, int groupCount)
    + run(): void
}

class Handler {
    + handle(Socket socket, SmtpWorker worker)
}

class SmtpWorker {
    SmtpWorker(Mail mail)
    + work(String message) : String
    - identity(): String
    - mailHeader(): String
    - mailBody(): String
}

enum SmtpProcedureStep {
    OPENING
    INIT_CLIENT
    INIT_SERVER
    MAIL_HEADER
    MAIL_DATA
}

enum SmtpServerCode {
    220
    221
    250
    354
}

class Parser {
    - Mail[] groups
    Parser(String victimFile, String messageFile, int groupCount)
    - selectMessage(): String
    - selectSender(): String
    - selectVictims(): String[]
    + getGroups(): Mail[]
    {static} - parseFile(String path) : String[]
}

class Mail {
    - String[] receivers
    - String message

    Mail(String[] receivers, String message)
    + getSender(): String
    + getReceivers(): String[]
    + getMessage(): String
}


Client ..> Handler
Client ..> Parser
Handler .down.> SmtpWorker
Parser ..> Mail
SmtpWorker "*" -right-> "1" Mail : "Message >"
SmtpWorker "*" -left-> "1" SmtpProcedureStep : "State >"
SmtpWorker .down.> SmtpServerCode
@enduml